export const ADD_NEW_FREELANCER_REQUEST = "ADD_NEW_FREELANCER_REQUEST";
export const ADD_NEW_FREELANCER_SUCCESS = "ADD_NEW_FREELANCER_SUCCESS";
export const SERVER_ERROR = "SERVER_ERROR";
export const GET_FREELANCER_SELF_PROFILE_REQUEST = "GET_FREELANCER_SELF_PROFILE_REQUEST";
export const GET_FREELANCER_SELF_PROFILE_SUCCESS = "GET_FREELANCER_SELF_PROFILE_SUCCESS";
