export const ADD_NEW_HIRER_REQUEST = "ADD_NEW_HIRER_REQUEST";
export const ADD_NEW_HIRER_SUCCESS = "ADD_NEW_HIRER_SUCCESS";
export const GET_VIEW_ALL_FREELANCER_REQUEST = "GET_VIEW_ALL_FREELANCER_REQUEST";
export const GET_VIEW_ALL_FREELANCER_SUCCESS = "GET_VIEW_ALL_FREELANCER_SUCCESS";