export const ADD_USER_CONTACT_REQUEST = "ADD_USER_CONTACT_REQUEST";
export const ADD_USER_CONTACT_SUCCESS = "ADD_USER_CONTACT_SUCCESS";
export const ADD_USER_SUBSCRIPTION_REQUEST = "ADD_USER_SUBSCRIPTION_REQUEST";
export const ADD_USER_SUBSCRIPTION_SUCCESS = "ADD_USER_SUBSCRIPTION_SUCCESS";
export const USER_SERVER_ERROR = "USER_SERVER_ERROR";